### ISSUE TITLE
error message on first-time openafter install

### ISSUE THREAD

**Issue by wilsonad32** [bookworm-devs/bookworm#14]
after installation completed and run bookworm for the first time, the following error message pop up. 

Fatal error detected
Failed to execute script pyi_rth_multiprocessing

It only happened on the first time run after installation. Subsequent run of bookworm will not produces this error message. Although not critical, hopes can't be fixed in the next release.

**Comment by mush42** [comment]
Hi @wilsonad32,

1. Please help me by including more information about your system.
2. Could you replicate the issue by uninstalling and reinstalling?
If you could, please attach the logs of that first run to your issue.

**Comment by wilsonad32** [comment]
hi, i can't replicate the issue by uninstalling and reinstalling. But, what did i experienced is the error message appears when the first time i install bookworm v0.1b2 and the second time was when install v0.1b3. It seems like everytime install a new version and the first-time open, the error message will appears but i don't notice any significant effect on the application itself. 

BTW, windows 10 home single language, 64bit.
