### ISSUE TITLE
support for html and txt

### ISSUE THREAD

**Issue by a-singer** [bookworm-devs/bookworm#30]
## Describe the solution you'd like

I would like to be able to open txt and html files in BW directly and to navigate through the HTML with headings, links, etc. 

## Describe alternatives you've considered

This can be done in notepad or a browser but BW has better functionality for reading and many books are in html and some are even in txt.

**Comment by mush42** [comment]
Hi @a-singer,

As a first step we can offer support for HTML documents with limited navigation functionality. My initial idea is to implement navigation by heading by listing headings in the Table of Content.

**Comment by a-singer** [comment]
Hi,

This sounds excellent. Would it be possible to have the headings as 
collapsed/expanded trees in the html file? That is, heading 1 would be 
at the first level, and if you hit right arrow on the heading, you would 
be at the heading two level with all the heading 2 headings under the 
heading 1 level and so on. Sorry to be so poor at the description, but I 
mean something like the books in multi-book epubs which have chapters 
within each book.
     As for TXT, obviously that wouldn't work, there is no way of 
getting navigation in them except maybe by percentage?
Thanks again for your work.

**Comment by mush42** [comment]
That's exactly what I'm thinking about.

**Comment by SeanTolstoyevski** [comment]
Hello,

My opinion for the TXT format:
It may be an idea to partition the contents of the file as we cannot obtain specific information such as the header.
For example, we can divide the 1 MB TXT file into 10 parts as 100 KB.
We produce a point that the user can refer to as in PDF files.
