### ISSUE TITLE
can't open bookworm after updated to b4

### ISSUE THREAD

**Issue by wilsonad32** [bookworm-devs/bookworm#32]
after install the update to b4, the recent update, i can't open the bookworm. when i open it, the following message displayed, 

Fatal error detected
Failed to execute script launcher
OK 

i have try restart computer and the error still persists. 

windows 10, 64bit,

**Comment by mush42** [comment]
Hi @wilsonad32,

This is a known issue. I'm currently looking at it.

Regards,
