### ISSUE TITLE
In the "Table of contents" tree view in the left pane of Bookworm, only level 1 items are tracked, but not level 2 ones

### ISSUE THREAD

**Issue by k-kolev1985** [bookworm-devs/bookworm#33]
## Describe the Problem

In some books, the table of contents contains not only chapters, but parent items, which in some cases are called "parts". So, a "part" can contain a few chapters. In such cases, Bookworm displays the "parts" as "level 1" items, and the chapters - as "level 2" items. If the book contains only chapters but not parts, the chapters are displayed by Bookworm as "level 1" items.

When Bookworm reads a book, whenever a new part/chapter is reached, the focus in the "Table of contents" tree view moves to the item corresponding to the respective part/chapter. But that is valid only for level 1 items. If the book contains not only chapters but parts as well (chapters are displayed as "level 2" items), Bookworm moves the focus in the "Table of contents" tree view only when a new part ("level 1" item) is reached. When a new chapter ("level 2" item) is reached, Bookworm does not change the focus to it in the "Table of contents" tree view. Is this intentional, a bug, or a technical limitation?

## To Reproduce

1. Launch Bookworm.
2. Load a book that contains not only chapters, but parts containing chapters as well (includes "level 2" items in the "Table of contents" tree view).
3. Start reading the book aloud with Bookworm (not via the screen reader).
4. Observe when the focus changes in the "Table of contents" tree view, when a new part and chapter is reached.

## Expected behavior

Bookworm should move the focus in the "Table of contents" tree view not only when a "level 1" item is reached, but when a "level 2" item is reached as well.

## The File You've Opened

Any EPUB or PDF file that contains "level 2" items in its "table of contents".

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1909 (build 18363.535), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b4, 32-bit, in bulgarian.

**Comment by mush42** [comment]
Hi @k-kolev1985,

This is the expected behavior. Traversing the whole tree for accurate highlighting might become very slow for books with deeply nested chapters. The latency cost of tree traversal is not justifiable.

I will keep this issue open for now. We may find an efficient way to do it in the future.

Regards,
