### ISSUE TITLE
Windows Error Sound Effect Occurs While Turning Pages

### ISSUE THREAD

**Issue by andy72039** [bookworm-devs/bookworm#40]
Hi, 

I'm using windows 10 with Bookworm 64bit and updated it to the latest version b4.
I found that every time I press Enter of Backspace to turn to the next/previous page, the windows error sound effect is played with the app's pagination sound. Even I unchecked the "Play pagination sound" in the Preferences, the error sound effect still occurs.

Thank you

**Comment by zersiax** [comment]
Why was this closed? This still happens for me when I arrow past  a page boundary.
